# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    webp:
        generate: true
    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [400, 220], mode: outbound }
        product_list:
            quality: 100
            filters:
                thumbnail: { size: [400, 500], mode: inset }
        admin_thumb:
            quality: 90
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: inset
