twig:
    file_name_pattern: '*.twig'
    globals:
        templateService: '@App\Service\TemplateService'
        tinymceApiKey: '%tinymceApiKey%'

when@test:
    twig:
        strict_variables: true
