vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /prod
            upload_destination: '%kernel.project_dir%/public/prod'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        newsImage:
            uri_prefix: /images/newsImage
            upload_destination: '%kernel.project_dir%/public/images/newsImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
